import test from 'node:test';
import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {createVoiceHandler,validateVoiceRequest,validateWav,takeAllowance} from '../api/voice.js';
import {encodeWav,resample,wavBase64} from '../src/voice-audio.js';
import {createHybridSpeechPlayer} from '../src/eleven-output.js';
import {createElevenInput} from '../src/eleven-input.js';

const wav=(seconds=1)=>Buffer.from(encodeWav(new Float32Array(16000*seconds).fill(.1)));
async function call({body={action:'speak',text:'Your briefing is ready.'},method='POST',headers={},env={ELEVENLAB_API_KEY:'test-secret'},fetcher=async()=>new Response(new Uint8Array([1,2,3]),{headers:{'Content-Type':'audio/mpeg'}}),allow=()=>true}={}){
  const req=Object.assign(new EventEmitter(),{method,body,headers:{origin:'https://fieldlens.test',host:'fieldlens.test','content-type':'application/json','sec-fetch-site':'same-origin',...headers}});
  const res=Object.assign(new EventEmitter(),{headers:{},setHeader(k,v){this.headers[k]=v;},end(value){this.body=value;this.writableEnded=true;}});
  await createVoiceHandler({env,fetcher,allow})(req,res);return res;
}
test('capability response exposes configuration only, never key',async()=>{const r=await call({method:'GET'});assert.equal(r.statusCode,200);assert.equal(JSON.parse(r.body).configured,true);assert.ok(!r.body.includes('test-secret'));assert.equal(r.headers['Cache-Control'],'private, no-store');});
test('missing or disabled provider remains explicit',async()=>{for(const env of [{},{ELEVENLAB_API_KEY:'test-secret',FIELDLENS_ELEVENLABS_DISABLED:'1'}]){const r=await call({env});assert.equal(r.statusCode,503);assert.equal(JSON.parse(r.body).code,'not_configured');}});
test('uses the existing singular key name and a fixed model and voice',async()=>{let sent;const r=await call({body:{action:'speak',text:'Hello.',voice:'attacker',model:'attacker',url:'https://example.com'},fetcher:async(url,options)=>{sent={url,options};return new Response(new Uint8Array([1]),{headers:{'Content-Type':'audio/mpeg'}});}});assert.equal(r.statusCode,200);assert.equal(sent.options.headers['xi-api-key'],'test-secret');assert.equal(JSON.parse(sent.options.body).model_id,'eleven_flash_v2_5');assert.match(sent.url,/api.elevenlabs.io\/v1\/text-to-speech\/EXAVIT/);assert.ok(!JSON.stringify(sent).includes('attacker'));});
test('methods, cross-origin, missing origin, and invalid content type fail before provider access',async()=>{for(const args of [{method:'PUT'},{headers:{origin:'https://evil.test'}},{headers:{origin:undefined}},{headers:{'sec-fetch-site':'cross-site'}},{headers:{'content-type':'text/plain'}}]){let called=false;const r=await call({...args,fetcher:async()=>{called=true;}});assert.ok([403,405,415].includes(r.statusCode));assert.equal(called,false);}});
test('request text and body limits reject before provider calls',async()=>{for(const args of [{body:{action:'speak',text:'x'.repeat(1201)}},{body:{action:'speak',text:''}},{body:{action:'unknown'}},{headers:{'content-length':'900001'}}]){let called=false;const r=await call({...args,fetcher:async()=>{called=true;}});assert.ok([400,413].includes(r.statusCode));assert.equal(called,false);}});
test('WAV codec produces bounded mono 16kHz audio with clamped samples',()=>{const a=Buffer.from(encodeWav(new Float32Array([-2,2,NaN,...new Array(2000).fill(0)])));assert.equal(a.readInt16LE(44),-32768);assert.equal(a.readInt16LE(46),32767);assert.equal(a.readInt16LE(48),0);assert.equal(validateWav(wav()),1);assert.equal(validateWav(wav(30)),20);});
test('control-only speech text is rejected after sanitizing',()=>{assert.throws(()=>validateVoiceRequest({action:'speak',text:'\u0000\u0001'}));assert.equal(validateVoiceRequest({action:'speak',text:'Hi\u0000 there'}).text,'Hi there');});
test('resampling preserves duration and constant amplitude',()=>{const a=resample(new Float32Array(48000).fill(.25),48000);assert.equal(a.length,16000);assert.ok(a.every(x=>x===.25));assert.equal(wavBase64(wav().buffer.slice(wav().byteOffset,wav().byteOffset+wav().length),s=>Buffer.from(s,'binary').toString('base64')).length>0,true);});
test('invalid audio metadata and encoded non-audio cannot be sent to provider',()=>{for(const mutate of [b=>b.writeUInt16LE(2,22),b=>b.writeUInt32LE(44100,24),b=>b.writeUInt32LE(0,40),b=>b.write('NOPE',0)]){const b=wav();mutate(b);assert.throws(()=>validateWav(b));}assert.throws(()=>validateWav(Buffer.alloc(10)));assert.throws(()=>validateVoiceRequest({action:'transcribe',audio:'not audio'}));assert.throws(()=>validateVoiceRequest({action:'transcribe',audio:Buffer.from('junk').toString('base64')}));});
test('transcription sends only bounded audio and returns only transcript text',async()=>{let form;const r=await call({body:{action:'transcribe',audio:wav().toString('base64'),source_url:'https://evil.test'},fetcher:async(url,options)=>{assert.equal(url,'https://api.elevenlabs.io/v1/speech-to-text');form=options.body;return Response.json({text:'From Reitz to Marston tomorrow at eight AM.',secret:'private provider metadata'});}});assert.equal(r.statusCode,200);assert.equal(form.get('model_id'),'scribe_v2');assert.equal(form.get('source_url'),null);assert.equal((await form.get('file').arrayBuffer()).byteLength,wav().length);assert.deepEqual(Object.keys(JSON.parse(r.body)),['text']);});
test('provider authentication errors never leak provider body or secret',async()=>{const r=await call({fetcher:async()=>Response.json({detail:{status:'missing_permissions',message:'test-secret'}},{status:401})});assert.equal(r.statusCode,503);assert.equal(JSON.parse(r.body).code,'provider_access');assert.ok(!r.body.includes('test-secret'));});
test('quota and malformed provider responses remain visible failures',async()=>{const limit=await call({fetcher:async()=>Response.json({detail:{status:'quota_exceeded'}},{status:401})});assert.equal(limit.statusCode,429);const bad=await call({fetcher:async()=>Response.json({oops:true})});assert.equal(bad.statusCode,502);});
test('IP allowance resets and enforces request and character budgets',()=>{const state=new Map();for(let i=0;i<40;i++)assert.equal(takeAllowance('ip',0,1,state),true);assert.equal(takeAllowance('ip',0,2,state),false);assert.equal(takeAllowance('ip',0,600001,state),true);assert.equal(takeAllowance('two',18001,1,state),false);});
test('rate limit avoids contacting ElevenLabs',async()=>{let called=false;const r=await call({allow:()=>false,fetcher:async()=>{called=true;}});assert.equal(r.statusCode,429);assert.equal(called,false);});

const tick=()=>new Promise(resolve=>setImmediate(resolve));
function audioHost(){const audios=[],spoken=[],revoked=[];class Audio{constructor(url){this.url=url;audios.push(this);}play(){return Promise.resolve();}pause(){this.paused=true;}load(){}removeAttribute(){}}class Utterance{constructor(text){this.text=text;}}return {audios,spoken,revoked,host:{Audio,SpeechSynthesisUtterance:Utterance,speechSynthesis:{cancel(){},speak(u){spoken.push(u);}},URL:{createObjectURL(){return 'blob:test';},revokeObjectURL(url){revoked.push(url);}}}};}
test('ElevenLabs output honors playback speed and cancels audio URLs',async()=>{const t=audioHost();const p=createHybridSpeechPlayer({host:t.host,fetcher:async()=>new Response(new Uint8Array([1]),{headers:{'Content-Type':'audio/mpeg'}})});p.setProvider('elevenlabs');p.speak('Hello',.85);await tick();assert.equal(t.audios[0].playbackRate,.85);p.cancel();assert.equal(t.audios[0].paused,true);assert.deepEqual(t.revoked,['blob:test']);assert.equal(p.active,false);});
test('late TTS response after Stop cannot start playback',async()=>{const t=audioHost();let resolve;const p=createHybridSpeechPlayer({host:t.host,fetcher:()=>new Promise(r=>resolve=r)});p.setProvider('elevenlabs');p.speak('Hello');p.cancel();resolve(new Response(new Uint8Array([1]),{headers:{'Content-Type':'audio/mpeg'}}));await tick();assert.equal(t.audios.length,0);assert.equal(t.spoken.length,0);});
test('TTS failure falls back to browser and never retries provider',async()=>{const t=audioHost(),notices=[];let calls=0;const p=createHybridSpeechPlayer({host:t.host,onNotice:m=>notices.push(m),fetcher:async()=>{calls++;return Response.json({message:'Quota reached'},{status:429});}});p.setProvider('elevenlabs');p.speak('Read this');await tick();assert.equal(calls,1);assert.equal(t.spoken[0].text,'Read this');assert.match(notices[0],/Browser voice/);p.cancel();});
test('changing service invalidates an in-flight TTS request',async()=>{const t=audioHost();let resolve;const p=createHybridSpeechPlayer({host:t.host,fetcher:()=>new Promise(r=>resolve=r)});p.setProvider('elevenlabs');p.speak('Old');p.setProvider('browser');p.speak('New');resolve(new Response(new Uint8Array([1]),{headers:{'Content-Type':'audio/mpeg'}}));await tick();assert.deepEqual(t.spoken.map(u=>u.text),['New']);assert.equal(t.audios.length,0);p.cancel();});

function captureHost(getUserMedia){const tracks=[{stopped:false,stop(){this.stopped=true;}}],nodes=[];const stream={getTracks:()=>tracks};class Context{constructor(){this.sampleRate=16000;this.audioWorklet={addModule:async()=>{}};}resume(){return Promise.resolve();}close(){this.closed=true;return Promise.resolve();}createMediaStreamSource(){return {connect(){},disconnect(){}};}}class Node{constructor(){this.port={};nodes.push(this);}connect(){}disconnect(){}}return {tracks,nodes,stream,host:{isSecureContext:true,navigator:{mediaDevices:{getUserMedia:getUserMedia||(async()=>stream)}},AudioContext:Context,AudioWorkletNode:Node,btoa:s=>Buffer.from(s,'binary').toString('base64')}};}
test('microphone recording sends one WAV after finish and stops all tracks',async()=>{const t=captureHost();let calls=0,reply;const input=createElevenInput({host:t.host,onResult:s=>reply=s,fetcher:async(url,options)=>{calls++;assert.equal(url,'/api/voice');const body=JSON.parse(options.body);assert.equal(body.action,'transcribe');validateVoiceRequest(body);return Response.json({text:'help'});}});await input.start();t.nodes[0].port.onmessage({data:new Float32Array(4096).fill(.1)});await input.finish();assert.equal(calls,1);assert.equal(reply,'help');assert.equal(t.tracks[0].stopped,true);assert.equal(input.active,false);});
test('Stop discards microphone audio without sending',async()=>{const t=captureHost();let calls=0;const input=createElevenInput({host:t.host,fetcher:async()=>{calls++;}});await input.start();t.nodes[0].port.onmessage({data:new Float32Array(4096).fill(.1)});input.cancel();await input.finish();assert.equal(calls,0);assert.equal(t.tracks[0].stopped,true);});
test('silence is not uploaded or interpreted as a trip',async()=>{const t=captureHost();let calls=0,message;const input=createElevenInput({host:t.host,onError:m=>message=m,fetcher:async()=>{calls++;}});await input.start();t.nodes[0].port.onmessage({data:new Float32Array(4096)});await input.finish();assert.equal(calls,0);assert.match(message,/No speech/);});
test('late microphone permission after cancellation immediately stops tracks',async()=>{let resolve;const t=captureHost(()=>new Promise(r=>resolve=r));const input=createElevenInput({host:t.host,fetcher:async()=>{throw Error('must not send');}});const starting=input.start();input.cancel();resolve(t.stream);await starting;assert.equal(t.tracks[0].stopped,true);assert.equal(input.active,false);});
test('late transcript after cancellation is ignored',async()=>{const t=captureHost();let resolve,reply;const input=createElevenInput({host:t.host,onResult:r=>reply=r,fetcher:()=>new Promise(r=>resolve=r)});await input.start();t.nodes[0].port.onmessage({data:new Float32Array(4096).fill(.1)});const finishing=input.finish();input.cancel();resolve(Response.json({text:'confirm'}));await finishing;assert.equal(reply,undefined);});
