import {formatDate,timeLabel,METHOD,relevantClosures} from './journey-model.js';
import {escapeHtml as esc} from './notebook.js';
import {icon,link} from './app-icons.js';
import {createClosureMonitor,mergeClosureSnapshot,compareClosureNotices,closureChangeText,CLOSURE_STALE_MS} from './closure-updates.js';
import {closureContent,closureSummary,closureSpeech} from './closure-view.js';
import {prefs,local,announce,createPageSpeech} from './app-shell.js';
import {SAVED_KEY as SAVED,writeJson} from './trip-state.js';
import './closure-updates.css';

export function mountBrief(bundle){
const {campus,grid}=bundle;
let brief=bundle.brief,saved=null,speaking=false,closureMonitoring=true,closureState='active',closureChange='';
const $=selector=>document.querySelector(selector),store=(key,value)=>writeJson(local,key,value);
const speechPlayer=createPageSpeech({onState(active){speaking=active;const button=$('#listen');if(button&&!button.disabled)button.innerHTML=active?icon('close')+' Stop listening':icon('sound')+' Listen to briefing';}});
const closureMonitor=createClosureMonitor({onData:applyClosureUpdate,onState(state){closureState=state;updateClosureStatus();if(state==='offline'&&brief)applyClosureUpdate({status:'unavailable'},{manual:false});}});
const visible=()=>closureMonitor.setVisible(!document.hidden),online=()=>closureMonitor.setOnline(navigator.onLine);
const hide=()=>{closureMonitor.stop();stopSpeech();},show=event=>{if(event.persisted&&brief)closureMonitor.start();};
document.addEventListener('visibilitychange',visible);window.addEventListener('online',online);window.addEventListener('offline',online);window.addEventListener('pagehide',hide);window.addEventListener('pageshow',show);
visible();online();
const staleTimer=setInterval(()=>{if(!document.hidden&&brief?.environment.closures.status==='available'&&Date.now()-Date.parse(brief.environment.closures.fetchedAt)>CLOSURE_STALE_MS)applyClosureUpdate({status:'unavailable'},{manual:false});},5000);
function surroundingText(section){
  if(section.coverage<.5||section.ndvi===null)return 'Not enough usable satellite data here';
  return section.ndvi>=.5?'Higher historical vegetation signal':section.ndvi>=.25?'Mixed historical vegetation signal':'Lower historical vegetation signal';
}
function surfaceText(section){const known=Object.entries(section.surfaces).filter(([k])=>k!=='unknown').sort((a,b)=>b[1]-a[1]);const unknown=Math.round((section.surfaces.unknown??0)/section.metres*100);return `${known.length?`Mapped surface tags include ${known.map(([s])=>s.replaceAll('_',' ')).join(', ')}.`:'Surface material is not recorded in this part of the map.'}${unknown&&known.length?` About ${unknown}% has no surface tag.`:''} These are map tags, not a recent inspection.`;}
function leadText(){const b=brief,w=b.weather;const temperature=Number.isFinite(w.low)?`${w.low===w.high?w.low:`${w.low} to ${w.high}`} degrees Fahrenheit`:'unavailable';return `${b.origin.name} to ${b.destination.name}. ${formatDate(b.departure)} at ${timeLabel(b.departure)} Eastern, with ${b.duration} minutes outdoors. ${w.status==='available'?`${w.description}. ${w.rain!==null?`The highest hourly rain chance during this window is ${w.rain}%.`:'Rain probability is unavailable.'} Air temperature: ${temperature}. Wind: ${w.wind||'unavailable'}.`:'Weather for your selected time is unavailable.'} ${closureSummary(b.closures)}`;}
function renderBrief(){const b=brief,w=b.weather,c=b.closures;const temp=w.low===null||w.low===undefined?'Unknown':w.low===w.high?`${w.low}°F`:`${w.low}–${w.high}°F`;const validAlerts=b.environment.alerts.status==='available'?b.environment.alerts.items.filter(a=>!a.expires||Date.parse(a.expires)>Date.now()):[];
  $('#results').innerHTML=`<div class="brief-heading"><div><p class="section-kicker">YOUR ENVIRONMENTAL BRIEFING</p><h2 id="brief-title" tabindex="-1">${esc(b.destination.name)},<br> <span>with the context you need.</span></h2><p class="trip-subtitle">From ${esc(b.origin.name)} · ${esc(formatDate(b.departure,{year:undefined}))} at ${esc(timeLabel(b.departure))} ET</p></div><span class="pilot-pill">CAMPUS PILOT</span></div>
    <div class="brief-tools"><button class="button button-primary" id="listen">${icon('sound')} Listen to briefing</button><button class="button button-outline" id="save-journey">${icon('bookmark')} Save journey</button><button class="icon-button" id="download" aria-label="Download briefing as a text file">${icon('download')}</button><span class="micro">Speech is optional. Escape stops audio.</span></div>
    <section class="summary-card card" aria-labelledby="summary-title"><div class="card-label">${icon('route')}<h3 id="summary-title">The short version</h3></div><p class="summary-text">${esc(leadText())}</p><div class="summary-bottom"><span>${icon('clock')} ${b.duration} min outdoors · your estimate</span><span>Prepared ${esc(timeLabel(b.createdAt))} ET</span></div></section>
    ${validAlerts.length?`<section class="alert-card card" aria-labelledby="alerts-title"><h3 id="alerts-title">Current official weather alerts</h3><p class="micro">Current alerts, not a prediction of alerts at your future departure.</p>${validAlerts.map(a=>`<details><summary>${esc(a.event)} · ${esc(a.severity)}</summary><p>${esc(a.headline)}</p><p>${esc(a.instruction||a.description)}</p><p>${link(a.source,'Read official alert')} · Expires ${esc(formatDate(a.expires,{hour:'numeric',minute:'2-digit'}))}</p></details>`).join('')}</section>`:''}
    <section class="weather-section card" aria-labelledby="weather-title"><div class="section-heading"><h3 id="weather-title">During your outdoor time</h3><span class="badge ${w.status==='available'?'forecast':'unknown'}">${w.status==='available'?'Forecast':'Unavailable'}</span></div><div class="weather-metrics"><div>${icon('rain')}<span>Hourly rain chance</span><strong>${w.status==='available'&&w.rain!==null?`${w.rain}%`:'Unknown'}</strong><small>${w.status==='available'&&w.rain!==null?'Highest hourly probability':'No probability available'}</small></div><div>${icon('sun')}<span>Air temperature</span><strong>${esc(temp)}</strong><small>Not surface temperature</small></div><div>${icon('wind')}<span>Wind</span><strong class="wind-value">${esc(w.wind||'Unknown')}</strong><small>Area forecast</small></div></div><p>${w.status==='available'?esc(w.description):esc(w.reason)}</p><p class="micro extra-detail">Forecast covers ${esc(timeLabel(b.departure))}–${esc(timeLabel(new Date(b.departure.getTime()+b.duration*60000)))} ET near the middle of this journey. NWS grid is approximately 2.5 km; this cannot identify puddles, slippery surfaces, or local gusts.</p><details><summary>Forecast source and hourly details</summary>${b.environment.weather.status==='available'?`<p>${link(b.environment.weather.source,'National Weather Service hourly forecast')} · Issued ${esc(formatDate(b.environment.weather.generatedAt,{hour:'numeric',minute:'2-digit'}))}; fetched ${esc(formatDate(b.environment.weather.fetchedAt,{hour:'numeric',minute:'2-digit'}))}.</p>${w.status==='available'?`<ul class="hourly-list">${w.periods.map(p=>`<li>${esc(timeLabel(p.start))}: ${esc(p.description)} · ${p.rain===null?'rain probability unknown':`${p.rain}% rain chance`}</li>`).join('')}</ul>`:''}`:`<p>The weather feed did not return usable data. ${link('https://forecast.weather.gov/MapClick.php?lat=29.6465&lon=-82.3478','Check the official Gainesville forecast')}.</p>`}<p>${b.environment.alerts.status==='available'?`${validAlerts.length} current alert${validAlerts.length===1?'':'s'} returned for the checked campus point. Check again before travel.`:'The current-alert feed could not be checked. An unavailable feed does not mean there are no warnings.'}</p></details></section>
    <section class="surroundings card" aria-labelledby="surroundings-title"><div class="section-heading"><h3 id="surroundings-title">Get a feel for the surroundings</h3><span class="badge historical">Sep 2024 context</span></div><p class="muted extra-detail">Three parts of a mapped study path—not navigation instructions. Satellite data describes vegetation, not what you can safely walk through.</p><ol class="journey-sections">${b.sections.map((section,index)=>`<li><span class="segment-marker" aria-hidden="true">${index+1}</span><div><span class="segment-label">${['STARTING OUT','ALONG THE WAY','NEAR YOUR DESTINATION'][index]}</span><h4>${surroundingText(section)}</h4><p class="extra-detail">${esc(surfaceText(section))}</p>${section.steps?'<p class="segment-warning">Steps are tagged in this part of the mapped path.</p>':''}${section.crossings?'<p class="micro">A crossing is mapped here. Signal accessibility and crossing conditions are not verified.</p>':''}<details><summary>Evidence for this section</summary><p>Length-weighted mean NDVI: ${section.ndvi===null?'unavailable':section.ndvi.toFixed(2)}. Valid-pixel coverage: ${Math.round(section.coverage*100)}%. Values summarize samples every 10 m along this third of the mapped line. ${link(grid.source,'Sentinel-2 scene, September 22, 2024')}.</p><p>Labels are descriptive bins, not validated classes: below 0.25 lower signal; 0.25–0.49 mixed; 0.50+ higher. No label is assigned below 50% valid coverage. Vegetation signal is not canopy, current shade, or a surface-safety measurement.</p><p>Surface tags: ${esc(Object.entries(section.surfaces).map(([s,n])=>`${s.replaceAll('_',' ')} ${Math.round(n)} m`).join('; '))}. ${link('https://www.openstreetmap.org/copyright','OpenStreetMap contributors')}; snapshot ${esc(formatDate(campus.retrievedAt))}.</p></details></div></li>`).join('')}</ol></section>
    <section class="closures-section card" id="closures-panel" aria-labelledby="closures-title"><div class="section-heading"><h3 id="closures-title" tabindex="-1">Campus closure updates</h3><span id="closure-badge" class="badge official">Official notices</span></div><p>Automatic checks every 15 seconds while this page is visible. Short shared caches and network delays apply. Updates depend on when UF publishes; this is not live pavement or obstacle sensing.</p><div class="closure-controls"><button type="button" class="button button-outline" id="closure-refresh">Check UF notices now</button><button type="button" class="button button-outline" id="closure-read">Listen to closure update</button></div><label class="check-row closure-auto"><input id="closure-auto" type="checkbox" ${closureMonitoring?'checked':''}>Automatically check UF notices</label><p id="closure-status" class="closure-status"></p><p id="closure-freshness" class="closure-freshness"></p><p id="closure-changes"></p><div id="closure-content">${closureContent(c)}</div><p>${link('https://campusclosures.ufl.edu/closure-home','Check all UF campus notices')}</p><p class="micro">Updates do not recalculate or certify an accessible detour. Weather and satellite information do not refresh with this feed. No automatic audio plays when a notice changes.</p></section>
    <section class="preparation card" aria-labelledby="preparation-title"><div class="section-heading"><h3 id="preparation-title">Prepare in your own way</h3><span class="badge neutral">Your choices</span></div><p>Optional reminders—not instructions about how you should travel. Nothing here changes your mobility equipment.</p><label class="check-row"><input type="checkbox">Check the latest forecast and official alerts before leaving.</label><label class="check-row"><input type="checkbox">${w.rain!==null&&w.rain>=30?'Consider my preferred rain protection and wet-weather footwear.':'Review the weather gear I prefer for this trip.'}</label><label class="check-row"><input type="checkbox">Allow the outdoor time and breaks that work for me.</label><label class="check-row"><input type="checkbox">Review any closure and confirm entrance access if needed.</label><p class="micro">Checklist stays with this briefing only. Cane-tip or grip modifications are not recommended by this app.</p></section>
    <section class="unknowns card" aria-labelledby="unknown-title"><div class="card-label">${icon('info')}<h3 id="unknown-title">What RealLens can’t verify</h3></div><p>Current puddles, pavement damage, temporary obstacles, safe crossings, exact shade, and entrance access. Forecast rain is not observed flooding. Satellite vegetation is not a safe-path rating.</p><p class="micro">The mapped study line is about ${Math.round(b.route.metres)} m, excluding unverified connections of approximately ${Math.round(b.route.startGap)} m and ${Math.round(b.route.endGap)} m from building centers to the network. It may include steps or closures. Do not use it as turn-by-turn guidance.</p></section>
    <details class="optional-map card" id="optional-map"><summary>${icon('route')} Optional map · see the study path<span>All essential information is above</span></summary><div id="map-container"></div><p class="micro">Map depicts OSM geometry, not a verified accessible route. ${link('https://www.openstreetmap.org/copyright','© OpenStreetMap contributors')} · snapshot ${esc(formatDate(campus.retrievedAt))}. No live position tracking.</p><a class="button button-outline" href="/explorer.html">Explore the separate Lake Alice 3D archive ${icon('arrow')}</a><p class="micro">Lake Alice is outside this campus pilot and is not part of this journey’s briefing.</p></details>`;
  $('#listen').disabled=!speechPlayer.supported;if($('#listen').disabled)$('#listen').innerHTML='Speech unavailable in this browser';
  $('#listen').addEventListener('click',()=>speaking?stopSpeech():speakBrief());
  $('#save-journey').addEventListener('click',()=>{saved={origin:b.origin.id,destination:b.destination.id,duration:b.duration};if(store(SAVED,saved)){$('#save-journey').innerHTML=`${icon('check')} Saved in this browser`;announce('Places and duration saved in this browser. Weather, date, and conditions are not saved.');}else announce('This browser could not save the journey. You can still download the briefing.');});
  $('#download').addEventListener('click',()=>{const blob=new Blob([briefText()],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='reallens-journey-briefing.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);announce('Briefing downloaded with sources and limitations.');});
  $('#optional-map').addEventListener('toggle',()=>{if($('#optional-map').open&&!$('#map-container').innerHTML)renderMap();});
  $('#closure-refresh').addEventListener('click',()=>void closureMonitor.refresh());
  $('#closure-auto').addEventListener('change',event=>{closureMonitoring=event.target.checked;closureMonitor.setEnabled(closureMonitoring);});
  $('#closure-read').disabled=!speechPlayer.supported;
  $('#closure-read').addEventListener('click',()=>{if(speaking)stopSpeech();else{speechPlayer.speak(closureSpeech(brief),prefs.rate);}});
  updateClosureStatus();
}
function updateClosureStatus(){
  if(!brief||!$('#closure-status'))return;
  const feed=brief.environment.closures,c=brief.closures;
  const states={checking:'Checking UF notices…',active:'Automatic checks on · every 15 seconds.',retrying:'UF check failed. Retrying automatically at longer intervals, up to two minutes.',paused:'Automatic checks paused. Use Check UF notices now.',hidden:'Checks paused while this page is hidden.',offline:'Offline. Updates cannot be checked.'};
  $('#closure-status').textContent=states[closureState]||states.active;
  $('#closure-refresh').setAttribute('aria-disabled',String(closureState==='checking'||closureState==='offline'));
  $('#closure-freshness').textContent=`${feed.fetchedAt?`Last successful source check: ${formatDate(feed.fetchedAt,{hour:'numeric',minute:'2-digit',second:'2-digit'})} Eastern.`:'No successful source check.'} ${c.status==='stale'?'Earlier notices are stale, not current.':c.status==='unavailable'?'Current notices unavailable.':''}`;
  const badge=$('#closure-badge');badge.textContent=c.status==='stale'?'Stale · not current':c.status!=='available'?'Unavailable':c.geometryStatus==='unavailable'?'Location relevance unknown':'UF published notices';badge.className=`badge ${c.status==='available'&&c.geometryStatus!=='unavailable'?'official':'unknown'}`;
  $('#closure-changes').textContent=closureChange;
}
function applyClosureUpdate(incoming,{manual=false}={}){
  if(!brief||!$('#closure-content'))return;
  const previous=brief.closures,oldFeed=brief.environment.closures,nextFeed=mergeClosureSnapshot(oldFeed,incoming);
  const next=relevantClosures(brief.route,nextFeed,brief.departure,brief.duration);
  const scoped=c=>[...c.matches,...(c.unmappedNotices||[])];
  const contentChanged=JSON.stringify(previous)!==JSON.stringify(next);
  let message='';
  if(next.status==='available'&&previous.status==='available')message=closureChangeText(compareClosureNotices(scoped(previous),scoped(next)));
  if(previous.status!==next.status)message=next.status==='available'?'UF closure updates are available again. Review the latest notices.':'UF closure updates could not be refreshed. Earlier notices are not current.';
  if(previous.geometryStatus!==next.geometryStatus&&next.status==='available')message=next.geometryStatus==='unavailable'?'UF notices were checked, but the closure map is unavailable. Location relevance is unknown.':'UF closure-map data is available again. Review the latest notices.';
  brief.environment.closures=nextFeed;brief.closures=next;
  if(contentChanged){
    stopSpeech();
    const body=$('#closure-content'),focused=body.contains(document.activeElement),href=focused?document.activeElement.getAttribute('href'):null;
    const opened=new Set([...body.querySelectorAll('details[open]')].map(d=>d.dataset.expand));
    body.innerHTML=closureContent(next);for(const d of body.querySelectorAll('details'))if(opened.has(d.dataset.expand))d.open=true;
    if(focused){const target=href?[...body.querySelectorAll('a')].find(a=>a.getAttribute('href')===href):null;(target||$('#closures-title')).focus({preventScroll:true});}
    $('.summary-text').textContent=leadText();if($('#optional-map').open)renderMap();else $('#map-container').innerHTML='';
  }
  if(message){closureChange=message;announce(message);}else if(manual)announce(next.status==='available'?'UF checked. No notice changes for this journey.':'UF could not be checked. Conditions remain unknown.');
  updateClosureStatus();
}
function briefText(){const b=brief;if(!b)return '';return `REALLENS · ENVIRONMENTAL JOURNEY BRIEFING\nPrepared ${formatDate(b.createdAt,{hour:'numeric',minute:'2-digit'})} Eastern\n\n${leadText()}\n\nSURROUNDINGS — SEPTEMBER 22, 2024 CONTEXT\n${b.sections.map((s,i)=>`Section ${i+1}: ${surroundingText(s)}. ${surfaceText(s)}${s.steps?' Steps are tagged here.':''}${s.crossings?' Crossings are mapped; accessibility and conditions are not verified.':''} Valid vegetation coverage ${Math.round(s.coverage*100)}%.`).join('\n')}\n\nCLOSURES\n${closureSpeech(b)}\n${[...b.closures.matches,...(b.closures.unmappedNotices||[])].map(n=>n.source).join('\n')}\n\nCURRENT ALERTS\n${b.environment.alerts.status==='available'?b.environment.alerts.items.filter(a=>!a.expires||Date.parse(a.expires)>Date.now()).map(a=>`${a.event}: ${a.instruction||a.headline} ${a.source}`).join('\n')||'No active alerts returned at preparation time; not a future guarantee.':'Current alert feed unavailable.'}\n\nLIMITATIONS\nPreparation only, not navigation or obstacle detection. The study path is not field-checked and may include steps or closures. Building-to-network gaps of approximately ${Math.round(b.route.startGap)} and ${Math.round(b.route.endGap)} meters are not verified. Refresh this briefing before travel. Surface damage, flooding, shade, crossing conditions, and entrances are unknown. No mobility-equipment modifications are recommended.\n\nSOURCES\nWeather: ${b.environment.weather.source??'Unavailable'}\nWeather issued: ${b.environment.weather.generatedAt??'Unknown'}\nClosures: https://campusclosures.ufl.edu/closure-home\nClosures fetched: ${b.environment.closures.fetchedAt??'Unavailable'}\nMap: © OpenStreetMap contributors, https://www.openstreetmap.org/copyright; retrieved ${campus.retrievedAt}\nSatellite: ${grid.source}\nCurriculum: ${METHOD}\n`;}
function stopSpeech(){speechPlayer.cancel();}
function briefSpeechText(){if(!brief)return '';let text=briefText().split('\n\nSOURCES')[0];if(prefs.detail==='short')text=text.replace(/\n\nSURROUNDINGS[^]*?\n\nCLOSURES/,`\n\nHistorical vegetation context is from September 2024, not current shade. ${brief.sections.some(s=>s.steps)?'Steps are tagged on the mapped study path.':''} ${brief.sections.some(s=>s.crossings)?'Crossings are mapped, but their accessibility and conditions are not verified.':''}\n\nCLOSURES`);text=text.replace(/https:\/\/\S+/g,'Source link is available in the text.');return text;}
function speakBrief(){if(brief){speechPlayer.speak(briefSpeechText(),prefs.rate);}}
function renderMap(){const b=brief;const all=b.route.coordinates.concat([b.origin.coord,b.destination.coord]);const minX=Math.min(...all.map(p=>p[0]))-.0015,maxX=Math.max(...all.map(p=>p[0]))+.0015,minY=Math.min(...all.map(p=>p[1]))-.001,maxY=Math.max(...all.map(p=>p[1]))+.001;
  const project=p=>[(p[0]-minX)/(maxX-minX)*760,(maxY-p[1])/(maxY-minY)*450];const points=coords=>coords.map(p=>project(p).map(n=>n.toFixed(1)).join(',')).join(' ');
  const visible=campus.ways.filter(w=>w.geometry.some(p=>p[0]>=minX&&p[0]<=maxX&&p[1]>=minY&&p[1]<=maxY));
  $('#map-container').innerHTML=`<svg class="study-map" viewBox="0 0 760 450" role="img" aria-label="Optional OpenStreetMap study path from ${esc(b.origin.name)} to ${esc(b.destination.name)}. This is not a verified accessible route."><rect width="760" height="450" fill="var(--map-ground)"/>${visible.filter(w=>!w.tags.highway).map(w=>`<polygon points="${points(w.geometry)}" fill="${w.tags.building?'var(--map-building)':w.tags.natural==='water'?'#c2dade':'var(--map-green)'}" stroke="var(--map-line)" stroke-width="1"/>`).join('')}${visible.filter(w=>w.tags.highway).map(w=>`<polyline points="${points(w.geometry)}" fill="none" stroke="var(--map-path)" stroke-width="3"/>`).join('')}${b.closures.matches.flatMap(n=>n.polygons.map(rings=>`<path d="${rings.map(r=>`M${points(r)}Z`).join(' ')}" fill="#bd563944" fill-rule="evenodd" stroke="#a84428"/>`)).join('')}<polyline points="${points(b.route.coordinates)}" fill="none" stroke="var(--accent)" stroke-width="5" stroke-linecap="round" stroke-dasharray="9 5"/>${[b.origin,b.destination].map((p,i)=>{const [x,y]=project(p.coord);return `<circle cx="${x}" cy="${y}" r="13" fill="var(--accent)" stroke="white" stroke-width="3"/><text x="${x}" y="${y+4}" fill="white" text-anchor="middle" font-size="12" font-weight="700">${i?'B':'A'}</text>`;}).join('')}<text x="20" y="28" fill="var(--ink)" font-size="12">N ↑ · MAPPED STUDY LINE, NOT NAVIGATION</text></svg><div class="map-labels"><span>A · ${esc(b.origin.name)}</span><span>B · ${esc(b.destination.name)}</span></div>`;
}

renderBrief();closureMonitor.start();
return {destroy(){brief=null;clearInterval(staleTimer);closureMonitor.stop();speechPlayer.destroy();document.removeEventListener('visibilitychange',visible);window.removeEventListener('online',online);window.removeEventListener('offline',online);window.removeEventListener('pagehide',hide);window.removeEventListener('pageshow',show);}};
}
