import {PREFERENCES_KEY,readingPreferences} from './home-model.js';
import './welcome.css';

const paths={leaf:'<path d="M20 3C9 2 3 7 4 14c1 6 10 8 14 0 2-4 2-8 2-11Z"/><path d="M4 21 15 9"/>',route:'<circle cx="5" cy="5" r="3"/><circle cx="19" cy="19" r="3"/><path d="M8 5h8a4 4 0 0 1 0 8H8a4 4 0 0 0 0 8h8"/>',sound:'<path d="m11 5-6 4H2v6h3l6 4V5Zm4 3a6 6 0 0 1 0 8m3-11a10 10 0 0 1 0 14"/>',sun:'<circle cx="12" cy="12" r="4"/><path d="M12 1v2m0 18v2M1 12h2m18 0h2M4 4l2 2m12 12 2 2M20 4l-2 2M6 18l-2 2"/>',info:'<circle cx="12" cy="12" r="9"/><path d="M12 11v6m0-10v1"/>',settings:'<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3"/><circle cx="15" cy="17" r="3"/>',home:'<path d="m3 10 9-7 9 7v11H3V10Zm6 11v-8h6v8"/>',arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',close:'<path d="m6 6 12 12M6 18 18 6"/>'};
const icon=name=>`<svg class="icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[name]}</svg>`;
let prefs=readingPreferences(null),storageAvailable=true;
try{prefs=readingPreferences(JSON.parse(localStorage.getItem(PREFERENCES_KEY)||'null'));}catch{storageAvailable=false;}
function applyPreferences(){document.documentElement.dataset.contrast=prefs.contrast?'high':'normal';document.documentElement.dataset.reading=prefs.large?'large':'normal';}
applyPreferences();
document.querySelector('#app').innerHTML=`
  <a class="skip-link" href="#welcome-main">Skip to FieldLens introduction</a>
  <header class="welcome-header"><a class="brand" href="/welcome" aria-label="FieldLens introduction"><span>${icon('leaf')}</span>FieldLens</a><span class="welcome-location">Made for the way you move.</span><div><a class="header-start" href="/">Open FieldLens ${icon('arrow')}</a><button class="round-button" id="reading-open" aria-label="Reading preferences">${icon('settings')}</button></div></header>
  <main id="welcome-main" tabindex="-1"><section class="welcome-hero" aria-labelledby="welcome-title"><div class="welcome-intro"><p class="welcome-pill">A little context goes a long way ${icon('sun')}</p><h1 id="welcome-title">How can<br> FieldLens help<br> you today?</h1></div>
    <div class="welcome-board"><div class="welcome-tiles"><a class="welcome-tile lime" href="/#overview"><span class="tile-heading"><span class="tile-icon">${icon('route')}</span><h2>Plan my<br>journey</h2></span><span class="tile-bottom">Before I head out <span aria-hidden="true">↗</span></span></a><a class="welcome-tile pink" href="/#voice-assistant"><span class="tile-heading"><span class="tile-icon">${icon('sound')}</span><h2>Talk to<br>FieldLens</h2></span><span class="tile-bottom">Ask in my own words <span aria-hidden="true">↗</span></span></a><a class="welcome-tile aqua" href="/#overview"><span class="tile-heading"><span class="tile-icon">${icon('sun')}</span><h2>Understand<br>the conditions</h2></span><span class="tile-bottom">Start with my journey <span aria-hidden="true">↗</span></span></a><a class="welcome-tile gray" href="/#method"><span class="tile-heading"><span class="tile-icon">${icon('info')}</span><h2>Know what’s<br>behind it</h2></span><span class="tile-bottom">Sources, not guesses <span aria-hidden="true">↗</span></span></a></div>
    <nav class="welcome-dock" aria-label="Quick navigation"><a class="dock-home" href="/">${icon('home')}<span>Home</span></a><a href="/#voice-assistant" aria-label="Open voice assistant">${icon('sound')}</a><a href="/explorer.html" aria-label="Open Lake Alice landscape explorer">${icon('leaf')}</a><a href="#how-it-works" aria-label="How FieldLens works">${icon('info')}</a></nav><p class="board-caption">Your journey. Your pace. Your choices.</p></div><div class="welcome-copy"><p class="welcome-description">Get a grasp of the environment on your way. Weather, surroundings, and campus changes—translated into useful context, in text or voice.</p><a class="start-link" href="/">Let’s look ahead <span>${icon('arrow')}</span></a><p class="audience-note">Designed with blind and low-vision travelers in mind.<br> Starting with six places on UF’s Gainesville campus.</p></div></section>
    <section class="welcome-how" id="how-it-works" aria-labelledby="how-title"><div><p class="eyebrow">LESS GUESSWORK. MORE CONTEXT.</p><h2 id="how-title">An environment briefing.<br>Not just another map.</h2></div><div class="how-steps"><article><span>01</span><h3>Tell us where and when.</h3><p>Choose two campus places and the time you expect to spend outdoors. No live location tracking.</p></article><article><span>02</span><h3>Understand what it means.</h3><p>Review forecast weather, published UF closures, and dated satellite vegetation. Unknowns stay visible.</p></article><article><span>03</span><h3>Read it. Or hear it.</h3><p>Ask by text, or choose to use voice. Microphone recording starts only when you ask and grant permission.</p></article></div></section>
    <aside class="welcome-boundary"><span>${icon('info')}</span><p><strong>Preparation, not navigation.</strong> FieldLens cannot detect obstacles or certify a safe or accessible route. This independent prototype has not yet been validated with blind or low-vision participants.</p><a href="/#method">Read the limitations ${icon('arrow')}</a></aside>
  </main><footer><a class="brand" href="/">FieldLens</a><p>Your environment, explained.</p><a href="/#method">Sources & privacy</a></footer>
  <dialog id="reading" aria-labelledby="reading-title"><div class="dialog-top"><h2 id="reading-title">Reading preferences</h2><button id="reading-close" class="round-button" aria-label="Close reading preferences">${icon('close')}</button></div><p>These choices also apply when you open FieldLens.</p><label><input type="checkbox" id="reading-large">Larger text</label><label><input type="checkbox" id="reading-contrast">Higher contrast</label><p id="reading-storage">Preferences stay in this browser.</p><button id="reading-done" class="done-button">Done</button></dialog>`;
const $=id=>document.getElementById(id);
$('reading-large').checked=prefs.large;$('reading-contrast').checked=prefs.contrast;
$('reading-open').addEventListener('click',()=>$('reading').showModal());
for(const id of ['reading-close','reading-done'])$(id).addEventListener('click',()=>$('reading').close());
function storageNote(){$('reading-storage').textContent=storageAvailable?'Preferences stay in this browser.':'This browser could not save preferences. Your choices apply to this page only.';}
for(const id of ['reading-large','reading-contrast'])$(id).addEventListener('change',()=>{prefs={...prefs,large:$('reading-large').checked,contrast:$('reading-contrast').checked};applyPreferences();try{localStorage.setItem(PREFERENCES_KEY,JSON.stringify(prefs));storageAvailable=true;}catch{storageAvailable=false;}storageNote();});
storageNote();
